# Generated by Django 4.2 on 2024-08-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_message_alter_mailing_options_mailing_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_datetime', models.DateTimeField(verbose_name='дата/время последней попытки')),
                ('status', models.CharField(choices=[('success', 'Удачно'), ('error', 'Ошибка')], max_length=15, verbose_name='статус')),
                ('response', models.CharField(max_length=100, verbose_name='ответ почтового сервера')),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='attempts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailings.attempt', verbose_name='попытки'),
        ),
    ]
