# Generated by Django 4.2 on 2024-08-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_attempt_mailing_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='attempts',
        ),
        migrations.AddField(
            model_name='attempt',
            name='mailing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mailings.mailing', verbose_name='рассылка'),
            preserve_default=False,
        ),
    ]
