# Generated by Django 4.2 on 2024-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_remove_mailing_attempts_attempt_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата/время первой отправки'),
        ),
    ]
